{% set version = "0.2.5" %}

package:
  name: nilearn
  version: {{ version }}

source:
  fn: nilearn-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: 6937a6c0aa83a65028532cbdb623bb53b8df569e6c3bb19308d78b5ef2cfb3d2

build:
    number: 2
    script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD 3-clause
  license_family: BSD
  summary: Statistical learning for neuroimaging in Python
  dev_url: https://github.com/nilearn/nilearn
  doc_url: https://nilearn.github.io

extra:
  recipe-maintainers:
    - lesteve
